name: GitHub Pages

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        run: |
          git fetch --prune --unshallow --tags
          git submodule update --init lib/zola.adidoks

      - name: Build GitHub Pages
        run: docker run -v ${{ github.workspace }}:/tmp -w /tmp ghcr.io/sapati/zola:v0.17.1-hu -r .github/pages build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.github/pages/public'

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
